"use client";

import React, { useState } from "react";
import type { NavigationTree, NavigationNode } from "@docspec/core";
import { ProjectSwitcher } from "../ui/ProjectSwitcher.js";

interface SidebarProps {
  navigation: NavigationTree;
  currentSlug?: string;
  artifacts?: Array<{ label: string; color?: string; version?: string }>;
  activeArtifact?: string;
  onArtifactChange?: (label: string) => void;
}

interface ExtendedNavigationNode extends NavigationNode {
  httpMethod?: string;
}

const HTTP_METHOD_COLORS: Record<string, { bg: string; text: string }> = {
  GET: { bg: "#dbeafe", text: "#1d4ed8" },
  POST: { bg: "#dcfce7", text: "#166534" },
  PUT: { bg: "#fef3c7", text: "#92400e" },
  PATCH: { bg: "#ffedd5", text: "#9a3412" },
  DELETE: { bg: "#fee2e2", text: "#991b1b" },
};

export function Sidebar({
  navigation,
  currentSlug,
  artifacts,
  activeArtifact,
  onArtifactChange,
}: SidebarProps) {
  return (
    <nav style={{
      width: 260,
      height: "100%",
      borderRight: "1px solid var(--ds-border, #e2e8f0)",
      background: "var(--ds-surface-primary, #ffffff)",
      display: "flex",
      flexDirection: "column",
      overflow: "hidden",
    }}>
      {/* Project Switcher at top */}
      {artifacts && artifacts.length > 0 && (
        <div style={{ padding: "12px 12px 0", borderBottom: "1px solid var(--ds-border, #e2e8f0)" }}>
          <ProjectSwitcher
            artifacts={artifacts}
            active={activeArtifact}
            onChange={onArtifactChange}
          />
        </div>
      )}

      {/* Scrollable nav content */}
      <div style={{ flex: 1, overflowY: "auto", padding: "8px 0" }}>
        {navigation.sections.map((section) => (
          <SidebarSection
            key={section.title}
            title={section.title}
            items={section.items}
            currentSlug={currentSlug}
          />
        ))}
      </div>

      {/* Footer */}
      <div style={{
        padding: "10px 16px",
        borderTop: "1px solid var(--ds-border, #e2e8f0)",
        fontSize: 10,
        color: "var(--ds-text-tertiary, #94a3b8)",
        fontFamily: "var(--font-mono, monospace)",
        letterSpacing: "0.02em",
      }}>
        Generated by DocSpec v3
      </div>
    </nav>
  );
}

function SidebarSection({
  title,
  items,
  currentSlug,
}: {
  title: string;
  items: NavigationNode[];
  currentSlug?: string;
}) {
  const [expanded, setExpanded] = useState(true);

  return (
    <div style={{ marginBottom: 8 }}>
      <button
        onClick={() => setExpanded(!expanded)}
        style={{
          display: "flex",
          alignItems: "center",
          width: "100%",
          padding: "6px 12px",
          border: "none",
          background: "transparent",
          cursor: "pointer",
          fontSize: 10.5,
          fontWeight: 600,
          textTransform: "uppercase",
          letterSpacing: "0.08em",
          color: "var(--ds-text-tertiary, #94a3b8)",
          transition: "color 0.15s ease",
        }}
      >
        <span style={{ flex: 1, textAlign: "left" }}>{title}</span>
        <svg
          width="10"
          height="10"
          viewBox="0 0 10 10"
          fill="none"
          style={{
            transform: expanded ? "rotate(90deg)" : "rotate(0deg)",
            transition: "transform 0.15s ease",
          }}
        >
          <path d="M3.5 2l3.5 3-3.5 3" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" />
        </svg>
      </button>
      {expanded && (
        <ul style={{ listStyle: "none", margin: 0, padding: 0 }}>
          {items.map((item) => (
            <SidebarItem
              key={item.slug || item.label}
              item={item as ExtendedNavigationNode}
              currentSlug={currentSlug}
              depth={0}
            />
          ))}
        </ul>
      )}
    </div>
  );
}

function SidebarItem({
  item,
  currentSlug,
  depth,
}: {
  item: ExtendedNavigationNode;
  currentSlug?: string;
  depth: number;
}) {
  const [expanded, setExpanded] = useState(true);
  const [hovered, setHovered] = useState(false);
  const normalizedSlug = item.slug?.replace(/^\//, "");
  const isActive = currentSlug === item.slug || currentSlug === normalizedSlug;
  const hasChildren = item.children && item.children.length > 0;

  const paddingLeft = depth * 12 + 12;

  return (
    <li style={{ listStyle: "none" }}>
      <div style={{ display: "flex", alignItems: "center" }}>
        {hasChildren && (
          <button
            onClick={() => setExpanded(!expanded)}
            style={{
              width: 20,
              height: 20,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              flexShrink: 0,
              border: "none",
              background: "transparent",
              cursor: "pointer",
              marginLeft: paddingLeft,
              padding: 0,
            }}
          >
            <svg
              width="10"
              height="10"
              viewBox="0 0 10 10"
              fill="none"
              style={{
                transform: expanded ? "rotate(90deg)" : "rotate(0deg)",
                transition: "transform 0.15s ease",
                color: "var(--ds-text-tertiary, #94a3b8)",
              }}
            >
              <path d="M3.5 2l3.5 3-3.5 3" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" />
            </svg>
          </button>
        )}
        <a
          href={item.slug ? (item.slug.startsWith("/") ? item.slug : `/${item.slug}`) : "#"}
          onMouseEnter={() => setHovered(true)}
          onMouseLeave={() => setHovered(false)}
          style={{
            flex: 1,
            display: "flex",
            alignItems: "center",
            paddingLeft: hasChildren ? 4 : paddingLeft + 20,
            paddingRight: 12,
            paddingTop: 5,
            paddingBottom: 5,
            fontSize: 13,
            fontFamily: "var(--font-body, 'Inter', sans-serif)",
            fontWeight: isActive ? 500 : 400,
            color: isActive
              ? "var(--ds-primary, #6366f1)"
              : "var(--ds-text-secondary, #475569)",
            background: isActive
              ? "var(--ds-primary-light, #eef2ff)"
              : hovered
                ? "var(--ds-surface-secondary, #f8fafc)"
                : "transparent",
            borderRadius: 4,
            textDecoration: "none",
            transition: "all 0.15s ease",
            marginLeft: 4,
            marginRight: 4,
          }}
        >
          {item.httpMethod && (
            <span style={{
              fontSize: 9,
              fontFamily: "var(--font-mono)",
              fontWeight: 600,
              padding: "1px 4px",
              borderRadius: 3,
              background: HTTP_METHOD_COLORS[item.httpMethod]?.bg || "#f1f5f9",
              color: HTTP_METHOD_COLORS[item.httpMethod]?.text || "#475569",
              marginRight: 6,
              letterSpacing: "0.03em",
            }}>
              {item.httpMethod}
            </span>
          )}
          {item.label}
        </a>
      </div>
      {hasChildren && expanded && (
        <ul style={{ listStyle: "none", margin: 0, padding: 0 }}>
          {item.children!.map((child) => (
            <SidebarItem
              key={child.slug || child.label}
              item={child as ExtendedNavigationNode}
              currentSlug={currentSlug}
              depth={depth + 1}
            />
          ))}
        </ul>
      )}
    </li>
  );
}
