// @docspec:module {
//   id: "docspec-ts-coverage-calculator",
//   name: "Coverage Calculator",
//   description: "Computes documentation coverage metrics by counting documented vs total classes, methods, and parameters. Produces a CoverageReport for inclusion in the DocSpec discovery section. Port of the Java CoverageCalculator.",
//   since: "3.0.0"
// }

/**
 * Calculates documentation coverage metrics for a TypeScript project.
 *
 * Mirrors the Java CoverageCalculator: tracks total vs. documented counts
 * for classes, methods, and parameters, then computes a coverage percentage.
 *
 * Coverage formula:
 *   coveragePercent = (documentedClasses / totalClasses) * 100
 *
 * Additional tracked metrics:
 *   - autoDiscoveredClasses: classes found by scanner without explicit annotations
 *   - annotatedClasses: classes with DocModule or similar decorators
 *   - inferredDescriptions: descriptions generated by DescriptionInferrer
 *   - method and parameter documentation rates
 *
 * @docspec:boundary "Documentation coverage metric computation"
 * @docspec:deterministic
 */
export interface CoverageReport {
  mode: string;
  frameworks: string[];
  scannedPackages: string[];
  excludedPackages: string[];
  totalClasses: number;
  documentedClasses: number;
  autoDiscoveredClasses: number;
  annotatedClasses: number;
  inferredDescriptions: number;
  totalMethods: number;
  documentedMethods: number;
  totalParams: number;
  documentedParams: number;
  coveragePercent: number;
}

export interface ModuleInput {
  id: string;
  name: string;
  members: MemberInput[];
}

export interface MemberInput {
  name: string;
  kind: string;
  description?: string;
  discoveredFrom?: string;
  methods?: MethodInput[];
}

export interface MethodInput {
  name: string;
  description?: string;
  params?: ParamInput[];
}

export interface ParamInput {
  name: string;
  description?: string;
}

export class CoverageCalculator {
  private totalClasses = 0;
  private documentedClasses = 0;
  private autoDiscoveredClasses = 0;
  private annotatedClasses = 0;
  private inferredDescriptions = 0;
  private totalMethods = 0;
  private documentedMethods = 0;
  private totalParams = 0;
  private documentedParams = 0;

  /**
   * Analyzes all modules and their members to compute coverage statistics.
   * @docspec:intentional "Iterates all modules, members, methods, and params to compute documentation coverage counters"
   */
  analyze(modules: ModuleInput[]): void {
    for (const module of modules) {
      for (const member of module.members) {
        this.totalClasses++;

        const hasDescription = !!member.description && member.description.trim().length > 0;
        if (hasDescription) {
          this.documentedClasses++;
        }

        // Track discovery source
        if (member.discoveredFrom === "annotation") {
          this.annotatedClasses++;
        } else if (member.discoveredFrom === "auto" || member.discoveredFrom === "framework") {
          this.autoDiscoveredClasses++;
        }

        // Analyze methods
        if (member.methods) {
          for (const method of member.methods) {
            this.totalMethods++;

            const hasMethodDesc = !!method.description && method.description.trim().length > 0;
            if (hasMethodDesc) {
              this.documentedMethods++;
            }

            // Analyze parameters
            if (method.params) {
              for (const param of method.params) {
                this.totalParams++;
                if (param.description && param.description.trim().length > 0) {
                  this.documentedParams++;
                }
              }
            }
          }
        }
      }
    }
  }

  /**
   * Increments the inferred description counter. Called by the processor
   * each time the DescriptionInferrer generates a description.
   * @docspec:preserves "Counter is monotonically increasing"
   */
  incrementInferredDescriptions(): void {
    this.inferredDescriptions++;
  }

  /**
   * Computes the coverage percentage for classes.
   * Returns a value between 0 and 100, rounded to one decimal place.
   * @docspec:deterministic
   * @docspec:preserves "Result in [0, 100]"
   */
  getCoveragePercent(): number {
    if (this.totalClasses === 0) return 0;
    return Math.round((this.documentedClasses / this.totalClasses) * 1000) / 10;
  }

  /**
   * Computes the coverage percentage for methods.
   * @docspec:deterministic
   * @docspec:preserves "Result in [0, 100]"
   */
  getMethodCoveragePercent(): number {
    if (this.totalMethods === 0) return 0;
    return Math.round((this.documentedMethods / this.totalMethods) * 1000) / 10;
  }

  /**
   * Computes the coverage percentage for parameters.
   * @docspec:deterministic
   * @docspec:preserves "Result in [0, 100]"
   */
  getParamCoveragePercent(): number {
    if (this.totalParams === 0) return 0;
    return Math.round((this.documentedParams / this.totalParams) * 1000) / 10;
  }

  /**
   * Generates a full coverage report suitable for inclusion in the DocSpec output.
   * @docspec:deterministic
   */
  toReport(
    mode: string,
    frameworks: string[],
    scannedPackages: string[] = [],
    excludedPackages: string[] = [],
  ): CoverageReport {
    return {
      mode,
      frameworks,
      scannedPackages,
      excludedPackages,
      totalClasses: this.totalClasses,
      documentedClasses: this.documentedClasses,
      autoDiscoveredClasses: this.autoDiscoveredClasses,
      annotatedClasses: this.annotatedClasses,
      inferredDescriptions: this.inferredDescriptions,
      totalMethods: this.totalMethods,
      documentedMethods: this.documentedMethods,
      totalParams: this.totalParams,
      documentedParams: this.documentedParams,
      coveragePercent: this.getCoveragePercent(),
    };
  }

  /**
   * Returns the summary counts for external use.
   * @docspec:deterministic
   */
  getSummary(): {
    totalClasses: number;
    documentedClasses: number;
    totalMethods: number;
    documentedMethods: number;
    totalParams: number;
    documentedParams: number;
  } {
    return {
      totalClasses: this.totalClasses,
      documentedClasses: this.documentedClasses,
      totalMethods: this.totalMethods,
      documentedMethods: this.documentedMethods,
      totalParams: this.totalParams,
      documentedParams: this.documentedParams,
    };
  }

  /**
   * Resets all counters. Useful for re-analysis.
   * @docspec:intentional "Resets all coverage counters to zero for fresh analysis"
   */
  reset(): void {
    this.totalClasses = 0;
    this.documentedClasses = 0;
    this.autoDiscoveredClasses = 0;
    this.annotatedClasses = 0;
    this.inferredDescriptions = 0;
    this.totalMethods = 0;
    this.documentedMethods = 0;
    this.totalParams = 0;
    this.documentedParams = 0;
  }
}
